server:
  port: 8081

spring:
  application:
    name: estoque-spring

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

jwt:
  secret: 4A2b8K9mP3xQ7rS5uV1yZ6cD8eF2gH9jL4nT7wX5aB1cM8pR
  expiration: 3600000
